=== CogitoGITHUB/dotfiles/lock-screen/schema/greeter.schema.json
{
  "$id": "lock-screen-greeter",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "lock-screen Greeter Config",
  "type": "object",
  "properties": {
    "user": { "type": "string", "description": "The default user." },
    "monitor": {
      "type": "string",
      "description": "The primary monitor with login field."
    },

    "animations": {
      "$ref": "#/$defs/animationProfile",
      "Title": "Default Animation Profile"
    },
    "fontFamily": {
      "type": "string",
      "description": "The monospace font to use."
    },
    "fakeIdentity": {
      "title": "Fake Identity",
      "type": "object",
      "description": "Configure the 'identity card' shown after logging in.",
      "properties": {
        "id": { "type": "string" },
        "class": { "type": "string" },
        "fullName": { "type": "string" }
      }
    },
    "fakeStatus": {
      "title": "Fake Status",
      "type": "object",
      "description": "Configure the status component in the top right.",
      "properties": {
        "env": { "type": "string" },
        "node": { "type": "string" }
      }
    },
    "modes": {
      "title": "Mode Settings",
      "type": "object",
      "description": "Mode specific settings",
      "properties": {
        "greetd": {
          "title": "Greetd Mode Settings",
          "type": "object",
          "properties": {
            "animations": { "$ref": "#/$defs/animationProfile" },
            "exit": {
              "description": "The command that is run to exit from the minimal compositor setup.",
              "type": "array",
              "items": { "type": "string" },
              "minItems": 1
            },
            "launch": {
              "description": "The command that is run after successful login, this should launch your main session (Hyprland, etc.)",
              "type": "array",
              "items": { "type": "string" },
              "minItems": 1
            }
          },
          "required": ["exit", "launch"]
        },
        "lockd": {
          "title": "Lockd Mode Settings",
          "type": "object",
          "properties": {
            "animations": { "$ref": "#/$defs/animationProfile" }
          }
        },
        "test": {
          "title": "Test Mode Settings",
          "type": "object",
          "properties": {
            "animations": { "$ref": "#/$defs/animationProfile" }
          }
        }
      },
      "required": ["greetd"]
    }
  },
  "required": ["modes"],

  "$defs": {
    "animationProfile": {
      "type": "string",
      "enum": ["reduced", "all"],
      "description": "UI animation profile: 'all' for full transitions, 'reduced' for no splash."
    }
  }
}

=== CogitoGITHUB/dotfiles/lock-screen/greeter.config.json
{
  "$schema": "https://raw.githubusercontent.com/TSM-061/ctOS/main/schema/greeter.schema.json",
  "user": "aoeu",
  "monitor": "eDP-1",
  "fontFamily": "Terminus",
  "fakeIdentity": {
    "id": "XYZ-843",
    "class": "L5_PROV",
    "fullName": "Blume Admin"
  },
  "fakeStatus": {
    "env": "Workstation",
    "node": "109.389.013.301"
  },
  "modes": {
    "greetd": {
      "animations": "all",
      "exit": ["pkill", "Hyprland"],
      "launch": ["Hyprland"]
    },
    "lockd": {
      "animations": "reduced"
    },
    "test": {
      "animations": "all"
    }
  }
}
